FILES_NUM=0
FILE_REGEXS=( '[sS][0-9]{2}[eE][0-9]{2}' '[0-9]{3}' '[0-9]x[0-9]{2}' '[0-9]{2}x[0-9]{2}' )
EXTENSION_REGEX='\.[A-Za-z0-9]*$'
COMPACT_EXTENSIONS=( ".rar" ".zip" )
SUB_EXTENSIONS='.srt'
MOV_EXTENSIONS='.mkv .mp4 .avi'
SUBS_BKP_DIR='Subs'
TORRENTS_BKP_DIR='Torrents'
SOURCES_BKP_DIR='Sources'
FILE_LIST=""
SPECIAL_CHARS_REGEX='[^A-Za-z0-9]'
